weights: /tutorials/Project/Group_Project_DL/Data/Data_For_Training/New_Data/Yolo_Evolve_21_22/train_evolve_21_22/yolov5x.pt
cfg: ''
data: /tutorials/Project/Group_Project_DL/Data/Data_For_Training/New_Data/data.yaml
hyp:
  lr0: 0.0115
  lrf: 0.0111
  momentum: 0.91001
  weight_decay: 0.00054
  warmup_epochs: 2.8389
  warmup_momentum: 0.76116
  warmup_bias_lr: 0.07306
  box: 0.04732
  cls: 0.52613
  cls_pw: 0.83385
  obj: 0.82512
  obj_pw: 1.1616
  iou_t: 0.2
  anchor_t: 3.9497
  fl_gamma: 0.0
  hsv_h: 0.01071
  hsv_s: 0.73437
  hsv_v: 0.35464
  degrees: 0.0
  translate: 0.14664
  scale: 0.45511
  shear: 0.0
  perspective: 0.0
  flipud: 0.0
  fliplr: 0.5
  mosaic: 0.84555
  mixup: 0.0
  copy_paste: 0.0
  anchors: 2.0
epochs: 112
batch_size: 32
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: cpu
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: ../../../../../Yolos/yolov5/runs/train
name: 2022_2021_Evolve_Train
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: ../../../../../Yolos/yolov5/runs/train/2022_2021_Evolve_Train
